server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuit4_baemin
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thdms1204
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

jwt:
  secret: "ZGVtbzEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6YWJjZGVmZw=="
  expiration: 3600000
